services:
    api-core:
        container_name: api-core
        build:
            context: .
            dockerfile: src/DemoShop.Api/Dockerfile
            target: dev
        command: [ "dotnet", "watch", "--no-restore", "run", "--no-restore", "--project", "src/DemoShop.Api/DemoShop.Api.csproj", "--urls", "http://+:3000" ]
        ports:
            - "3000:3000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:3000
            - SENTRY__DSN=${SENTRY_DSN}
            - KEYCLOAK__REALM=demo_shop
            - KEYCLOAK__RESOURCE=demo_shop_api_core
            - KEYCLOAK__AUTHSERVERURL=http://keycloak:8080
            - CONNECTIONSTRINGS__DEFAULTCONNECTION=${DB_CONNECTION}
        networks:
            - backend-net
            - frontend-net
            - messaging-net
        volumes:
            - ./:/app
            - /app/src/DemoShop.Api/bin/
            - /app/src/DemoShop.Api/obj/
            - /app/src/DemoShop.Application/bin/
            - /app/src/DemoShop.Application/obj/
            - /app/src/DemoShop.Domain/bin/
            - /app/src/DemoShop.Domain/obj/
            - /app/src/DemoShop.Infrastructure/bin/
            - /app/src/DemoShop.Infrastructure/obj/
            - nuget-packages:/root/.nuget/packages
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: 768M
                reservations:
                    memory: 384M

networks:
    backend-net:
        external: true
    frontend-net:
        external: true
    messaging-net:
        external: true

volumes:
    nuget-packages:
